export const marcas = [
  "Toyota",
  "Fiat",
  "Ford",
  "Renault",
  "Honda",
  "Chevrolet",
  "Volkswagen",
  "Nissan",
  "Kia",
  "Hyundai",
];
<<<<<<< HEAD
=======

>>>>>>> d11233413003fab785303559cb2c65333753da21
export const modelos = [
  { marca: "Fiat", modelo: "Pulse" },
  { marca: "Fiat", modelo: "Toro" },
  { marca: "Fiat", modelo: "Cronos" },
  { marca: "Fiat", modelo: "Mobi" },
  { marca: "Fiat", modelo: "Argo" },
  { marca: "Toyota", modelo: "Corolla" },
  { marca: "Toyota", modelo: "Hilux" },
  { marca: "Toyota", modelo: "SW4" },
  { marca: "Toyota", modelo: "Yaris" },
  { marca: "Toyota", modelo: "Camry" },
  { marca: "Ford", modelo: "Ranger" },
  { marca: "Ford", modelo: "Fiesta" },
  { marca: "Ford", modelo: "Ford Ka" },
  { marca: "Ford", modelo: "Ecosport" },
  { marca: "Ford", modelo: "Edge" },
  { marca: "Chevrolet", modelo: "Onix" },
  { marca: "Chevrolet", modelo: "Celta" },
  { marca: "Chevrolet", modelo: "Cruze" },
  { marca: "Chevrolet", modelo: "Corsa" },
  { marca: "Chevrolet", modelo: "Tracker" },
  { marca: "Renault", modelo: "Kwid" },
  { marca: "Renault", modelo: "Logan" },
  { marca: "Renault", modelo: "Sandero" },
  { marca: "Renault", modelo: "Duster" },
  { marca: "Renault", modelo: "Stepway" },
  { marca: "Volkswagen", modelo: "Polo" },
  { marca: "Volkswagen", modelo: "Gol" },
  { marca: "Volkswagen", modelo: "Fox" },
  { marca: "Volkswagen", modelo: "Golf" },
  { marca: "Volkswagen", modelo: "Taos" },
  { marca: "Hyundai", modelo: "HB20" },
  { marca: "Hyundai", modelo: "Tucson" },
  { marca: "Hyundai", modelo: "Creta" },
  { marca: "Hyundai", modelo: "iX35" },
  { marca: "Hyundai", modelo: "Santa Fe" },
  { marca: "Nissan", modelo: "March" },
  { marca: "Nissan", modelo: "Frontier" },
  { marca: "Nissan", modelo: "Sentra" },
  { marca: "Nissan", modelo: "Versa" },
  { marca: "Nissan", modelo: "Leaf" },
  { marca: "Honda", modelo: "City" },
  { marca: "Honda", modelo: "Fit" },
  { marca: "Honda", modelo: "Civic" },
  { marca: "Honda", modelo: "Accord" },
  { marca: "Honda", modelo: "CR-V" },
  { marca: "Kia", modelo: "Cerato" },
  { marca: "Kia", modelo: "Sportage" },
  { marca: "Kia", modelo: "Sorento" },
  { marca: "Kia", modelo: "Picanto" },
  { marca: "Kia", modelo: "Soul" },
];
